version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_server
    restart: always
    ports:
      - "8050:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - network_server

  mysql:
    image: mysql:8.0 
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitfood
      MYSQL_USER: aluno
      MYSQL_PASSWORD: 123456789

    ports:
      - "3306:3306"
    command: --port=3356
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - network_server

  phpmyadmin:
    image: phpmyadmin:5.2 
    container_name: phpmyadmin_server
    restart: always
    ports:
      - "8051:80"
    environment:
      PMA_HOST: mysql 
      PMA_PORT: 3356 
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - network_server


networks:
  network_server:
    driver: bridge


volumes:
  mysql_data: