version: '3.8'

services:
  apache:
    build:
      context: ./apache
    container_name: apache_redes
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_redes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: fitfood
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_redes
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: