version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Mapeia a porta 80 do container para a porta 8000 no host
    volumes:
      - .:/var/www/html # Monta o diretório atual no container
    depends_on:
      - db 

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fitfood 
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db 
volumes:
  db_data: # Define o volume nomeado para persistência de dados do banco